redhat-developer/vscode-yaml

server/src/languageService/services/schemaValidator.ts
Fixed issue where nodes with additionalProperties would error in specific cases
=> Fixed issue where nodes with additionalProperties would error in specific cases

package.json
This commit updates the description field in package.json so the
published extension has a better visibility and clear messaging,
wrt Kubernetes and Kedge information.
=> Update package.json with Kubernetes and Kedge info

README.md
This commit updates the README with the information on how to use
the recently added Kedge support added to yaml-language-server by
adding a short example snippet and additional information.
=> Update README with Kedge information

README.md, package-lock.json, package.json
Should have been done alongside the logo update 2 months ago.
=> Rename extension's displayName to 'YAML'

package-lock.json, package.json, src/extension.ts
Fix for https://github.com/redhat-developer/vscode-yaml/issues/156
=> Allow for no reload when installing in vscode

package.json
It was referencing the "languageServerExample".
=> Update the "yaml.trace.server" description

README.md
Let me know if anything is incorrect.
=> How to develop with YAML LS and VSCode together.

syntaxes/yaml.tmLanguage.json
I used http://json2plist.sinaapp.com/ for conversion
=> updates tmLanguage file from source

README.md
I had trouble figuring out how to load a local schema file until I read through #80 
To save future confusion I added an example to the README.md file.
=> Adding local schema file example to README.md

language-configuration.json, src/extension.ts, src/schema-contributor.ts
* Moved wordPattern language feature from extension.ts to language-configuration.json, so that it would be together with other declarative language features, removed relevant `languages` import
* Corrected comments that were seemingly left over from Microsoft's lsp-sample project and added more comments for clarification
=> Improve code clarity

package-lock.json, package.json, src/extension.ts
Updates the typescript version used and
also cleans up unused imports
Signed-off-by: Gorkem Ercan <gorkem.ercan@gmail.com>
=> update TS and clean unused imports

README.md, package-lock.json, package.json
Fixes: https://github.com/redhat-developer/vscode-yaml/issues/129
This PR and https://github.com/redhat-developer/yaml-language-server/pull/147 are a pair.
=> Update packages and say what JSON schema version we support

package-lock.json, package.json, src/extension.ts, src/schema-contributor.ts
This change updates the vscode-uri dependency to be consistent with yaml-language-server
=> Update and use vscode-uri

src/extension.ts
Reverts redhat-developer/vscode-yaml#194 because of https://github.com/redhat-developer/yaml-language-server/pull/170#issuecomment-522250737
=> Revert "Add workspace YAML files request handler"

README.md, package.json
Updates the package.json and README for kedge references
fixes #185
=> remove references to kedge

.travis.yml
Related to: https://github.com/redhat-developer/vscode-yaml/pull/316
=> Fix travis to use newer version of node and typescript

package-lock.json, test/schemaProvider.test.ts, test/testFixture/completion/schemaProvider.yaml
This PR adds a few new tests for the register contributor label api
=> Implement tests for register contributor label arg

Jenkinsfile
=> Deploy to open-vsx.org during releases

CHANGELOG.md, package-lock.json, package.json
=> Update to 0.10.1

src/extension.ts
Part of https://github.com/redhat-developer/yaml-language-server/pull/315
For: https://github.com/redhat-developer/yaml-language-server/issues/283
=> Add 'editor.tabSize' to preference synchronisation

CHANGELOG.md, README.md, package-lock.json, package.json
Signed-off-by: Yevhen Vydolob <yvydolob@redhat.com>
=> Release '0.11.0'

package-lock.json, package.json
Sorry, I totally forgot to update `yaml-language-server` dependency version.
=> Use latest yaml-language-server

CHANGELOG.md, package-lock.json, package.json
Bug fix release to fix https://github.com/redhat-developer/vscode-yaml/issues/366
=> Release '0.11.1'

src/extension.ts
A second PR to fix https://github.com/redhat-developer/yaml-language-server/issues/329, first PR https://github.com/redhat-developer/yaml-language-server/pull/332
=> Add '[yaml]' to settings syncronization

CHANGELOG.md, package-lock.json, package.json
Set version to `0.13.0` and add changelog
=> Release '0.13.0'

Jenkinsfile
Add check that 'publishToMarketPlace' is set during Jenkins CI build
=> Check that 'publishToMarketPlace' is set during Jenkins CI build

package.json
Set 'editor.autoIndent' preference to "keep" value 
Fix: #445
=> Set 'editor.autoIndent' to "keep" value

CONTRIBUTING.md, README.md
Updates the Readme and syncs with the YAML LS.
Moves contribution information to its own file.
Removes the Travis CI badge.
fixes #468
=> Update Readme for consistency

package-lock.json, package.json
Update VS Code version to `1.52.0` as it minimum version which works with  `vscode-languageclient`: `7.0.0`
Fix: #471
=> Update vscode version

README.md
Update README with way to disable CodeLens
=> Update README with way to disable CodeLens

CHANGELOG.md, package.json
> Note: telemetry will be released in `0.19.1` when PR's will be merged.
=> Release '0.19.0'

.github/workflows/CI.yaml
Use yarn on GH action, upload vsix artifact
=> Use yarn on GH action, upload vsix artifact

.github/workflows/default-branch-migration.yml
Add GH Workflow for default branch migration, new default brunch will be `main`
for #520
=> Add GH workflow for default branch migration

.github/workflows/CI.yaml, README.md
Use 'main' as default brunch in GH Actions
Resolve #520
=> Use 'main' as default brunch in CI

package.json
#500 
* After we configured "redhat.vscode-yaml" in extensionDependencies it won't work on versions below 1.57.0
=> feat: support workspace trust

package.json
Enable support of virtual workspaces.
I make some manual tests and it seems that vscode-yaml works file with virtual workspaces
Resolve: #502
manually, just follow https://github.com/microsoft/vscode/wiki/Virtual-Workspaces
=> Add capability to support virtual workspaces

.github/CODEOWNERS
Remove @joshuawilson from code owners
=> Remove joshuawilson from code owners

.github/workflows/CI.yaml, CHANGELOG.md, CONTRIBUTING.md, Jenkinsfile
Bug fix release to fix https://github.com/redhat-developer/vscode-yaml/issues/633
=> Release '1.1.1'

package.json, yarn.lock
Upgrade `request-light` library with fix for redirect issue.
Fix: https://github.com/redhat-developer/vscode-yaml/issues/586
manually
=> Upgrade 'request-light' version

.github/CODEOWNERS, Jenkinsfile
It's my last day at Red Hat so I'm removing myself from the codeowners
=> Remove jpinkney from codeowners

package.json, yarn.lock
Integrating latest request-light lib
https://github.com/redhat-developer/yaml-language-server/issues/588
=> integrated the latest 0.5.7 request-light lib version

README.md
Adds the information about relative path usage on modeline schema association.
fixes #587
Doc update
=> improve modeline doc

CHANGELOG.md, src/node/yamlClientMain.ts
=> Release 1.6.0

package.json
Update bump version 1.7.0
No ref
=> update bump version 1.7.0

Jenkinsfile
Same as https://github.com/redhat-developer/vscode-yaml/pull/758 but for stable version
=> Use sftp to upload stable vsix file

.github/workflows/CI.yaml, .gitignore, package.json, test/ui-test/allTestsSuite.ts, test/ui-test/common/YAMLConstants.ts, test/ui-test/extensionUITest.ts, yarn.lock
- include ui tests into CI workflow
- bring new ui-test script option to run ui tests
- update .gitignore to omit test-resources dir
Signed-off-by: Ondrej Dockal <odockal@redhat.com>
=> Introduce UI tests using vscode-extension-tester

CHANGELOG.md
=> release 1.8.0

package.json
bump version to 1.9.0
no ref
NA
=> updated bump version to 1.9.0

Jenkinsfile
publish the pre-release vscode-yaml extension
https://github.com/redhat-developer/vscode-yaml/issues/682
NA
=> added pre release in jenkins

CHANGELOG.md, package.json
=> release 1.9.1

CONTRIBUTING.md, README.md
Signed-off-by: Mohit Suman <mohit.skn@gmail.com>
Updates the readme badges including version, installs, workflow and openvsx downloads
=> update readme badges and add feedback links

README.md, package.json
Adds the `yaml.style.FlowMapping` and `FlowSequence`
options.
N/A
User testing and UTs on yaml-language-server
=> Expose the new flow style options

package.json
Signed-off-by: Ondrej Dockal <odockal@redhat.com>
=> Restrict vscode version run by UI tests

package.json
=> bump version 1.11.0

package.json, src/telemetry.ts, yarn.lock
Upgraded vscode version to 1.63.0 for support pre-release
https://github.com/redhat-developer/vscode-yaml/issues/819
https://github.com/redhat-developer/vscode-yaml/issues/796
NA
=> 796 yaml build issue

Jenkinsfile
Signed-off-by: msivasubramaniaan <msivasub@redhat.com>
This PR publish the pre-release as universal one
https://github.com/ansible/vscode-ansible/issues/615
https://github.com/redhat-developer/vscode-yaml/issues/819
NA
=> published pre-release as universal version

.vscode/launch.json, custom-settings.json, test/ui-test/allTestsSuite.ts, test/ui-test/contentAssistTest.ts
Fixes #802
Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>
=> Add first UI test

test/ui-test/allTestsSuite.ts, test/ui-test/customTagsTest.ts
Fixes #837
Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>
=> Create UI test for testing YAML custom tags

test/ui-test/allTestsSuite.ts, test/ui-test/contentAssistTest.ts, test/ui-test/customTagsTest.ts, test/ui-test/schemaIsSetTest.ts
Fixes #850 
Please review @msivasubramaniaan
=> Create UI test for testing whether the right schema has been selected

test/ui-test/Utilities.ts, test/ui-test/allTestsSuite.ts, test/ui-test/autocompletionTest.ts, test/ui-test/customTagsTest.ts, test/ui-test/schemaIsSetTest.ts
Fixes #853
Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>
=> Create UI test for testing whether the autocompletion works

CHANGELOG.md
Signed-off-by: msivasubramaniaan <msivasub@redhat.com>
release vscode-yaml v1.11.0
NA
NA
=> release v1.11.0

package.json
Signed-off-by: msivasubramaniaan <msivasub@redhat.com>
bump version to 1.12.0
NA
NA
=> bump v1.12.0

README.md
Fix the bug on the `build` badge on the README page.
Closes #865 
No changes to source code; only for docs.
=> Fix bug in badge for README

CHANGELOG.md
=> updated changelog.md for release 1.12.0

CHANGELOG.md
=> updated changelog.md for release 1.12.1

src/recommendation/openShiftToolkit.ts
Added null check
Cannot read properties of undefined (reading 'findIndex')
Yes
=> Msivasubramaniaan patch 1

CHANGELOG.md
=> changelog updated for release 1.12.2

CHANGELOG.md, package.json
=> updated changelog.md for release 1.13.0

CHANGELOG.md, package.json
=> Release 1.14.0

package.json, yarn.lock
To restrict sending startup events to 1 daily only
=> Update telemetry to 0.8.0

package.json, yarn.lock
As the release has been pointed to `release` branch, so revert the main branch YAML LS points to future build
NA
NA
=> revert YAML LS versions

package.json
Add filename .clang-tidy as YAML
https://github.com/redhat-developer/vscode-yaml/issues/1052
=> Add filename .clang-tidy as YAML

package.json
Bump version 1.17.0 as v1.16.0 released
NA
NA
=> bump v1.17.0

package.json
=> Bump v1.18.0

CHANGELOG.md
[ChangeLog](https://github.com/redhat-developer/vscode-yaml/blob/main/CHANGELOG.md) updated for the release 1.18.0
No Ref
NA
=> updated changelog for the release 1.18.0

src/extension.ts
Fix the prettier error (error generated due to code formatting )
#1117
CI
=> Fix build failure due to prettier error

CHANGELOG.md
Adds the CHANGELOG entry for 1.19.0
N/A
Existing test cases
=> CHANGELOG for 1.19.0

CHANGELOG.md, package-lock.json, package.json
CHANGELOG for 1.19.1
none
no code changes
=> CHANGELOG for 1.19.1
