- src/extension.ts
In preparation for [Visual Studio Live Share](https://aka.ms/vsls) adding support for "guests" to receive remote language services for YAML files, this PR simply updates the current `DocumentSelector` to be limited to `file` and `untitled` (unsaved) files. This way, when someone has the YAML extension installed, and joins a Live Share session (where files use the `vsls:` scheme), their language services will be entirely derived from the remote/host side, which provides a more accurate and project-wide experience (guests in Live Share don't have local file access to the project they're collaborating with).
*Note: I made the same change for the [Java LSP client](https://github.com/redhat-developer/vscode-java/pull/492) as well.*
> [Discussion] [Live Share] Restrict language services to local files

- src/extension.ts
Send DynamicCustomSchemaRequestRegistration request so that VSCode registers with the language server to use custom schema requests. This is because some clients were getting errors when the server was sending CustomSchemaRequest types to the client.
Corresponding PR on yaml-language-server side https://github.com/redhat-developer/yaml-language-server/pull/94
> Send DynamicCustomSchemaRequestRegistration request

- language-configuration.json
> Fixed ragion markers not showing

- src/extension.ts
We're writing an extension that depends on this one and when starting in debug mode within VSCode there is an error that causes our extension not to start:
I've tracked it down to an outdated `--debug` flag passed to the language server running in Node. Now that VSCode is running v8.9.3 that has switched to `--inspect`.
After this change starting this extension with the "Launch Extension" task then works:
> Fix debug flag breaking in latest VSCode

- README.md
Corresponding PR: https://github.com/redhat-developer/yaml-language-server/pull/112
> Fixed readme for custom tags fix in YAML LS

- README.md
- package.json
This PR adds the ability to enable/disable pulling well known schemas from the JSON schema store.
> Added yaml.schemaStore setting to enable/disable schema store connection

- src/extension.ts
This allows the server to send a 'custom/workspace/yamlfiles' request and receive a list of absolute paths to all YAML files in the workspace.
Useful for external tools that need to know the file paths to provide smarter validation / auto-completion than feasible with JSON schema.
The implementation would be highly specific to the tools themselves, so this isn't a complete, but an enabling feature.
> Add workspace YAML files request handler

- src/extension.ts
In the Kubernetes extension we would like to get YAML hover on 'live' resources, viewed on the cluster via a `FileSystemProvider` rather than saved to the filesystem first.  The YAML extension currently registers the language server only for filesystem and untitled documents.  This PR amends that to register it for all YAML documents.
> Support URL schemes other than file or untitled

- README.md
- Assure JSON snippets are valid and use correct marker
- Document use of full-paths via file:/// uri
- Document support for multiple glob patterns in examples
Fixes: #259
> Improved documentation on schema configuration

- src/schema-extension-api.ts
- test/schemaProvider.test.ts
This PR allows a yaml file to be matched with multiple contributors.
This is then handled on the yaml language server side by https://github.com/redhat-developer/yaml-language-server/pull/227
> Allow multiple matches for one yaml file with requestCustomSchema

- README.md
This PR adds a configuration example in README.md, to use "yamlValidation" feature in package.json from another extension
> Added a "yamlValidation" example in documentation

- Jenkinsfile
- test/testRunner.ts
This PR is grabbed from: https://github.com/snjeza/vscode-yaml/commit/95727e3f9171af75d1668265633fd22b692a090b
and then cherry-picked onto master so that tests will pass
(cherry picked from commit 95727e3f9171af75d1668265633fd22b692a090b)
Supercedes https://github.com/redhat-developer/vscode-yaml/pull/316
> Allow tests to run on jenkins again

- src/schema-extension-api.ts
In case when two(or more) extensions wants to contribute JSON Scheme for same file, we need a way to chose which scheme LS will use. This PR solve that problem by adding additional optional parameter for `registerContributor` method.
That parameter is `label`, it should contains yaml key value pair, that pair will be used to check file content and LS receive only one JSON scheme, if label is match.
Fix: https://github.com/redhat-developer/yaml-language-server/issues/267
> Add label for scheme contributions

- README.md
A small error, but I configured `yaml.customTags` based on this description without looking at the correct example below, and was left confused for a few minutes when the tags configured as `"!Tag map"` still trigger unknown tag errors.
> Fix error in yaml.customTags documentation in README.md

- src/schema-extension-api.ts
- test/schemaProvider.test.ts
in case, one of the registered is throwing an error, it avoids to break
the other registered ones.
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> Catch errors that can be thrown by registered schema providers #323

- src/schema-extension-api.ts
- test/schemaProvider.test.ts
Reverts redhat-developer/vscode-yaml#324 so that we can merge https://github.com/redhat-developer/vscode-yaml/pull/327 instead
> Revert "Catch errors that can be thrown by registered schema providers #323"

- src/extension.ts
- src/schema-extension-api.ts
for instance, currently with VS Code Kubernetes extension which is throwing error with ```- ``` file content:
requires https://github.com/redhat-developer/vscode-yaml/pull/324
> Use an output channel

- test/schemaProvider.test.ts
After https://github.com/redhat-developer/vscode-yaml/pull/330, and then https://github.com/redhat-developer/vscode-yaml/pull/327 was merged instead, we need to re-add the schema provider test
> Re-add multiple contributors error test

- package-lock.json
- package.json
Major vulnerability in mochoa@8.0.1 -> mocha@8.1.1.
Minor vulnerability in minimist --depth 2. Autofix updated the package-lock.
> fix npm dependency vulnerability

- .github/workflows/CI.yaml
- test/completion.test.ts
- test/helper.ts
This Action only build PR, for three main OS.
> Add GitHub Action to build PR

- Jenkinsfile
- package-lock.json
- package.json
- scripts/check-dependencies.js
This PR changes version of `yaml-language-server` to `next` which allow use the latest changes in [yaml-language-server](https://github.com/redhat-developer/yaml-language-server)
> Use 'next' version of yaml-ls

- package-lock.json
- src/extension.ts
- src/paths.ts
This PR is the client side part of https://github.com/redhat-developer/vscode-yaml/issues/387. Majority of it was taken from vscode-json-languageserver with minor modifications
https://github.com/redhat-developer/vscode-yaml/issues/387
Add in:
```
"yamlValidation": [
{
"fileMatch": ["test.yml", "test.yaml"],
"url": "https://gist.githubusercontent.com/JPinkney/fbbb95f3708e8b33f81267b243981ff6/raw/09af433aff3972f5d72cfe5c69951e94c1497875/kubernetes-console.json"
}
]
```
under the "contributes" section of the package.json, then test the extension and make sure that the kubernetes schema is used for both test.yml and test.yaml (it might take a few seconds to load because the schema is so big)
> Allow array for fileMatch in yamlValidation contribution

- Jenkinsfile
Change Node.JS version for Jenkins build.
We use Jenkins to perform release.
> Set 'nodejs-12.20.0' for Jenkins

- package-lock.json
- package.json
- src/extension.ts
This PR is the client-side request to https://github.com/redhat-developer/yaml-language-server/pull/359. The client-side handles the schema downloading and sending the information back to the yaml language server
https://github.com/redhat-developer/vscode-yaml/issues/107
The only way I know how to test this is on the Red Hat VPN.
You'll need the server side changes: https://github.com/redhat-developer/yaml-language-server/pull/359
Once you connect to the VPN these schemas should resolve correctly
```
"yaml.schemas": {
"https://gitlab.cee.redhat.com/cpaas/service/-/raw/development/resources/schemas/release-root.json": "release.yml",
"https://gitlab.cee.redhat.com/cpaas/service/-/raw/development/resources/schemas/product-root.json": …
```
> Add in non-standard lsp request for resolving schemas on the client-side

- Jenkinsfile
Fixes an issue where artifacts are published into the wrong folder:
`vscode-yaml staging` is now pushed to /snapshots/vscode-yaml
`vscode-yaml stable` is now pushed to /stable/vscode-yaml
https://github.com/redhat-developer/vscode-yaml/issues
> Publish artifacts to correct location

- src/extension.ts
It set `revealOutputChannelOn` option to `Never`, to disable reveal of `YAML Support` Output channel 
#359
manually with forcing yaml-ls to throw errors
> Set output channel to never reveal

- package-lock.json
- package.json
- src/extension.ts
- src/json-schema-cache.ts
- src/json-schema-content-provider.ts
- src/schema-extension-api.ts
Add implementation for text document content provider which handle `json-schema` URI shema, to open JSON Schema in VScode editor
> Note: to be able to open files from LS this PR also update `vscode-languageclient` to `7.0.0` version
#174
> Add custom text document content provider

- test/helper.ts
Avoid an warning message as:
[exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
> Fix runtime warning on configuration loading

- README.md
- src/extension.ts
- src/json-schema-content-provider.ts
- src/schema-extension-api.ts
- test/json-shema-content-provider.test.ts
Add ability to open JSON Schema content contributed by other extensions with ExtensionAPI.
Depends on https://github.com/redhat-developer/yaml-language-server/pull/424
https://github.com/redhat-developer/yaml-language-server/issues/412
With test. To manual test, open any yaml which has json schema contributed with ExtensionAPI(any k8s yaml with k8s extension installed) and click on codelens over first line, it should open JSON Schema in editor tab.
> Load schema content contributed by other extensions

- src/extension.ts
- src/json-schema-cache.ts
- src/json-schema-content-provider.ts
Trying to fix return undefined from schema cache.
I cannot reproduce #462 on my laptop, it seems that it is can be related to OS and file system.
This PR ensures that if we receive 304 HTTP status whe check JSON Schema content and for some reasons cache doesn't contains content, we just load again it from server.
#462 
Manually on Mac. It would be nice if reviews can test it on other systems.
Just open any yaml files with schema from schema store associated with it, and make sure that schema loaded.
> Fix returning undefined from cache

- README.md
Just change GH Action badge to old one as current is not supported in `vsce` tool and release build failing with message:
```
ERROR  SVGs are restricted in README.md; please use other file image formats, such as PNG: https://github.com/redhat-developer/vscode-yaml/actions/workflows/CI.yaml/badge.svg
```
It seems that GH changes URL for badges and new URL is not supported in `vsce`, [details]( https://github.com/microsoft/vscode-vsce/issues/553)
> Change GH Action badge URL

- package-lock.json
- package.json
To avoid switching between lockfileVersion 2 and 1, we require minimal version of npm.
Based on similar change merged on:
https://github.com/microsoft/vscode-json-languageservice/pull/95/files
> Require minimal npm version

- README.md
- package.json
Adds option to configure schema store catalogue endpoint
Depends on https://github.com/redhat-developer/yaml-language-server/pull/459
Fixes #406
Fixes #294
Untested(?)
> feat: add setting for schema store url

- .vscode/launch.json
- .vscode/tasks.json
- src/extension.ts
- src/json-schema-cache.ts
- test/helper.ts
- test/json-schema-cache.test.ts
Add cache cleanup if cached file was deleted from fs.
Also add some tests for cache class.
Remove useless  launch config.
> Clean schema cache if file was deleted

- src/extension.ts
- yarn.lock
It changes the way how LS receives settings/preferences.
With https://github.com/redhat-developer/yaml-language-server/pull/476 yaml-ls will fetch settings with [workspace configuration request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration)
Fix #478
> remove deprecated 'configurationSection'

- .vscode/launch.json
- README.md
- USAGE_DATA.md
- package.json
- src/extension.ts
- src/telemetry.ts
- test/telemetry.test.ts
- yarn.lock
Restore telemetry collection without the need for vscode-commons. See #515.
Fixes #458 for good
When debugging the yaml extension, check telemetry events in:
- host debug console
- https://app.segment.com/redhat-devtools/sources/vs_code_tests/debugger
> Restore telemetry

- package.json
- yarn.lock
Update vscode-redhat-telemetry to 0.2.0
This allows using vscode-yaml in clients with vscode API < 1.55
Fixes #537
Install vsix in vscode 1.54, check #537 is fixed
> Update vscode-redhat-telemetry to 0.2.0

- src/telemetry.ts
- test/telemetry.test.ts
Changes based on @fbricon feedback:
- Ignore `Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment ` message
- Remove `[Error - 2:04:53 PM]` from telemetry error message start
none
with tests
> Improve telemetry

- package.json
- yarn.lock
Update vscode-redhat-telemetry to 0.4.2
- reduces the amount of identify events sent to segment.com
- better identify unique users on gitpod
- when running in extension development host, the host debug console will display "vscode-redhat-telemetry: Skipping 'identify' event! Already sent:" logs, after reloading. A hash of the identify event will be stored under %Code location%/User/globalStorage/vscode-redhat-telemetry/cache
> Update vscode-redhat-telemetry to 0.4.2

- .gitignore
- .prettierignore
- .vscode/launch.json
- .vscode/tasks.json
- .vscodeignore
- package.json
- src/extension.ts
- webpack.config.js
- yarn.lock
This PR based on https://github.com/redhat-developer/vscode-yaml/pull/591 @fbricon work.
It just add bundling of yaml-ls in `languageserver.js` file.
>Note: I keep `prettier` unbundled as it contains quite big and already bundled files.
For me vscode shows `78ms` activation time with this PR, comparing to `303ms` for `0.22.0` version
And `vsix` file now contains 50 files, 4.23MB size, comparing to 1829 files, 8.5MB for `0.22.0`.
The only thing that we may loose that error stack traces now doesn't contains any readable names, so it would be hard to find problem if user/telemetry report any trace.
redhat-developer/vscode-yaml#521
> Add code bundling with webpack

- src/telemetry.ts
- test/telemetry.test.ts
It combines errors messages, and send them as one to telemetry
none
with tests
> Throttle LSP error telemetry reporting

- README.md
- package.json
- test/helper.ts
- test/json-schema-cache.test.ts
- test/telemetry.test.ts
- yarn.lock
Add new preference `yaml.yamlVersion`, which contains default YAML spec version. 
Also it updates `yarn.lock` to use latest yaml-language-server with new YAML parser
Resolve: https://github.com/redhat-developer/vscode-yaml/issues/396
> Add setting for yaml spec version

- package.json
- src/extension.ts
For some reason VSCode provide own language mode for docker compose files - https://github.com/microsoft/vscode/blob/main/extensions/yaml/package.json#L17
This PR add activation event for `dockercompose` language mode and bind yaml-ls to it.
none
manually
> Start extension on 'dockercompose' language mode

- .yarnrc
- package.json
- src/extension.ts
- src/schema-status-bar-item.ts
- test/helper.ts
- test/json-schema-selection.test.ts
- webpack.config.js
- yarn.lock
Add new status bar item in VSCode status bar. This status bar shows current schema used and allow to select/switch schema with UI (quick pick box). It also indicate with error background if yaml-ls uses more than one schema for file.
Demo:
https://user-images.githubusercontent.com/929743/141985832-d207df10-9a26-48c1-99cb-f9edd327180b.mov
Depends on https://github.com/redhat-developer/yaml-language-server/pull/556
Resolve: redhat-developer/vscode-yaml#565
With test
> Add status bar item for JSON schema selection

- README.md
- package.json
Add config to exclude not required default props from completion (**default is set to false (previous functionality)**).
The reason why users appreciated this feature is that users don't have to specify default properties. Only if the default value needs to be changed, it makes sense to add them (but not all of them automatically).
https://github.com/redhat-developer/yaml-language-server/pull/606
In ref PR
> feat: add disableDefaultProperties

- package.json
Add 'telemetry' tag to redhat.telemetry.enabled preference, so the Red Hat telemetry setting can show up in VS Code's Telemetry settings, like in:
> Add 'telemetry' tag to redhat.telemetry.enabled preference

- src/schema-status-bar-item.ts
- test/json-schema-selection.test.ts
Adds support for versions in JSON Schema store.
Depends on https://github.com/redhat-developer/yaml-language-server/pull/675
Resolve https://github.com/redhat-developer/yaml-language-server/issues/639
> Support JSON Schema versions from schemastore

- README.md
Adds new way to include local schema for **Windows System**
In windows, the existing way to use local schema is non-clickable, meaning VS Code does not recognized the local path to file and opens target file, which is simple way to validate if everything is correct.
On Windows System,
Please point to your local schema in the format `file:///C:/path/to/local/schema.json` . Example:
```
"yaml.schemas": {
"file:///C:/schema.json": "*.yaml",
```
> Alternate way to add local schema in windows

- CONTRIBUTING.md
Some improvements to contributing guidelines to make it easier to start debugging out of the box - closes #745.
* Update the language server to the ts file to avoid having to compile the language server project for each change
* Removed the unnecessary compile step (its done anyway in the pre-launch when debugging the extension)
* Added a line to update the outFiles of the server launch config to the correct path
* Added a note to fix an issue I ran into when debugging where I had a port clash with another plugin
> Improvements to the contributing instructions

- src/extension.ts
- src/node/yamlClientMain.ts
- src/webworker/yamlClientMain.ts
Removes `yaml.server.initialized` and send `startup` instead 
Resolve #725
> Send startup event on LS start

- Jenkinsfile
On Jenkins we have problem with uploading `vsix` file to staging server, this PR use `sftp` 
none, found during `1.7.0` release
> Use sftp to upload vsix file

- README.md
- package.json
Adds the setting for parent Skeleton order that is available from the YAML LS when doing code assists.
https://github.com/redhat-developer/yaml-language-server/pull/691
Tested on YAML LSP, catching up with the settings.
> add parent skeleton setting

- package.json
According to the [VSCode configuration schema](https://code.visualstudio.com/api/references/contribution-points#Configuration-schema), the `.contributes.configuration.title` property seems to be required and is currently missing 
in vscode-yaml. This PR adds the title to configuration.
None
- `npm install`
- `npm run build`
- `vsce package`
Then add `.vsix` to VSCode, made sure extension still works on YAML and I verified configuration still has the YAML settings there (and only once). Also clicked the 'extension settings' from the extensions list and I also got to all the YAML settings.
> Add title to extension configuration

- src/schema-extension-api.ts
Changes the signature of `ExtensionAPI.requestSchemaContent` to include `Promise<string>` as a return value since the internal interface and the implementation supports it.
It's not that relevant, but makes it more obvious to users that this is an option.
> Fix signature of ExtensionAPI.requestSchemaContent

- USAGE_DATA.md
- package.json
- yarn.lock
Update vscode-redhat-telemetry to 0.5.1
Makes red Hat telemetry abide by VS Code's own telemetry settings. Also allows remote configuration of telemetry. See https://github.com/redhat-developer/vscode-redhat-telemetry#remote-configuration
Tested manually. Check telemetry is disabled if "telemetry.telemetryLevel":"off". If set on "crash"/"errror", only errors will be reported.
> Update vscode-redhat-telemetry to 0.5.1

- package.json
- yarn.lock
... to prevent excessive sending of identify events
> Update vscode-redhat-telemetry to 0.5.2

- README.md
- package.json
Adds the config property for enforcing alphabetical key ordering of maps
n/a
existing tests
> Add map key order config

- .github/workflows/CI.yaml
Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
Rebased from #875
> Pin 3rd-party actions to SHA1

- .vscode/launch.json
- CONTRIBUTING.md
- src/node/yamlClientMain.ts
Since vscode-yaml depends on yaml-language-server directly, the latest version will always be under node_modules. For contributors, it's convenient to test against an instance built from sources. Assume local instance is in a sibling directory called 'yaml-language-server'.
@msivasubramaniaan , let me know if this makes sense. It should be easier to run a local instance this way.
> Make it easier to build latest/custom yaml-language-server.

- package.json
- src/extension.ts
- src/recommendation/dependencyAnalytics.ts
- src/recommendation/handler.ts
- src/recommendation/handlerImpl.ts
- src/recommendation/index.ts
- src/recommendation/openShiftToolkit.ts
- webpack.config.js
This PR recommends [OpenSift Toolkit ](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-openshift-connector)extension when the workspace folder contains 'devfile.yaml'
https://github.com/redhat-developer/vscode-openshift-tools/issues/2592
Yes with UT
> OpenShift Toolkit extension recommendation

- .gitignore
- .vscode/launch.json
- package.json
- src/webworker/yamlClientMain.ts
- test/telemetry.test.ts
- webpack.config.js
- yarn.lock
Enables Telemetry when the extension runs in a Web browser
No linked issue
Best way to test this is to run a CLI build:
```
yarn build
```
Then launch an http server and create a tunnel to expose it online. In one terminal run:
```
npx serve --cors -l 5000
```
This will start a web server on port 5000. Then, in a second terminal, execute: 
```
npx localtunnel -p 5000
```
This will expose your local web server to a public URL like `https://<fancy-name>-<your-IP>.loca.lt`
Copy that URL, open it in a browser, click on the button to enable it.
Then go to https://vscode.dev, if you already have redhat.vscode-yaml installed, uninstall it. 
With the command palette (Ctrl+Shift+P/Cmd+Shift+P on mac), run the `Developer: Install Extension from …
> Enable telemetry in Web extension

- README.md
- src/recommendation/openShiftToolkit.ts
Added try, catch block for lstatSync()
https://github.com/redhat-developer/vscode-yaml/issues/904
Yes
> added try catch block on lstatSync

- src/json-schema-content-provider.ts
- Correctly reads proxy settings from vscode user settings
https://github.com/redhat-developer/vscode-yaml/issues/920
https://github.com/redhat-developer/vscode-yaml/issues/694
Tested manually by providing many proxy combinations.
Test steps:
- In vscode, open user settings tab: `F1 -> Preferences: Open User Settings -> Application -> Proxy`
- Pick `Proxy Support` to one of `on`, `fallback`, `override`
- Write your specific proxy address, which is different than the one in HTTP_PROXY or HTTPS_PROXY environment variables.
- Try to access resource which is only available when using the proxy.
> Fixed proxy support

- README.md
Fixes the wrong name on the Readme for maxItemsComputed.
> Fix maxItemsComputed settings name

- package.json
- src/extension.ts
Adds the `yaml.kubernetesSchemaUrls` setting and its corresponding notification to support multiple custom kubernetes versions and Custom Resource Definitions (CRDs).
https://github.com/redhat-developer/yaml-language-server/pull/841
- Manually building this vscode extension and the linked yaml language server and then using/testing it.
> Support Multiple Custom Kubernetes Versions and CRDs

- package.json
- src/extension.ts
Reverts redhat-developer/vscode-yaml#912
> Revert "Support Multiple Custom Kubernetes Versions and CRDs"

- CHANGELOG.md
- package.json
> updated changelog and versions for release 1.15.0

- package.json
- test/schemaProvider.test.ts
- yarn.lock
Signed-off-by: David Thompson <davthomp@redhat.com>
Fix the integration test for hover
The integration test for hover
It's a fix to a test
> Adjust to new hover behviour for enum

- src/schema-extension-api.ts
- tsconfig.json
Updated eslint version to support replaceAll method
https://github.com/redhat-developer/vscode-yaml/issues/1078
Existing test case
> changed replace to replaceAll on schema

- CHANGELOG.md
changelog updated for the release v1.17.0
NA
NA
> changelog updated for the release v1.17.0

- package.json
- src/extension.ts
Start and link extension to the `github-actions-workflow` language.
Fixes https://github.com/redhat-developer/vscode-yaml/issues/1086
Related to https://github.com/github/vscode-github-actions/issues/195
I didn't properly test it. I followed https://github.com/redhat-developer/vscode-yaml/pull/648 and https://github.com/redhat-developer/vscode-yaml/pull/1093 as reference.
> Add language `github-actions-workflow`

- test/ui-test/customTagsTest.ts
This PR uses delays in order to get the "YAML custom tags works as expected" test passing consistently.
My best guess as to why this works is that it takes bit of time for the setting change to propagate to the language server.
Fixes #1119
Run the UI tests locally. Before this PR, they should fail consistently, and after this PR, they should pass consistently.
> Stabilize UI tests

- .github/workflows/CI.yaml
- .vscodeignore
- package-lock.json
- package.json
- src/extension.ts
1. The `l10n` folder, which contains all the translations, was not present anywhere in the built .vsix. The translations are required in order to run yaml-language-server, so I copied from yaml-language-server to `dist/l10n`.
2. The location of l10n was listed as `../yaml-language-server/l10n`. This doesn't work if yaml-language-server isn't cloned locally, and doesn't work when running as a .vsix, so I changed it to `./dist/l10n`.
3. During the CI run, npm isn't installing the latest prerelease of yaml-language-server. I added a step to force it to use the latest yaml-language-server. This is important, because the above bugs could have been caught earlier if we were actually testing against the newest yaml-language-server.
Fixes #1152
Yes, with the existing test suites.
> l10n missing from .vsix
